# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: detect-aws-credentials
  - id: detect-private-key
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: check-xml
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-symlinks

- repo: https://github.com/ansible/ansible-lint
  rev: v4.3.4
  hooks:
  - id: ansible-lint

- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.4
  hooks:
  - id: shellcheck

- repo: https://github.com/IamTheFij/docker-pre-commit
  rev: v2.0.0
  hooks:
  - id: hadolint
